# repo_url: https://github.com/northshorewc/ccr2016
copyright: North Shore Water Commission &copy; 2021 - <a href='http://www.northshorewater.org'><i>visit us at www.northshorewater.org</i></a>
remote_branch: gh-pages
site_url: https://northshorewc.github.io/ccr2020
site_author: Eric Kiefer
site_name: 2020 Annual Water Quality Report
# google_analytics: ['UA-93001027-2','auto']
theme: readthedocs
# theme_dir: readthedocs-theme
# theme: material
# theme_dir: material-theme
extra_css:
  - css/extra.css

extra_javascript:
  - js/fontAwesome.js
  - js/mathjax.js
  - js/mathjax-config.js
  - js/sticky.js
  - js/jquery-min.js
  - js/jquery-min-migrate.js
  - js/slick-min.js
  - js/extra.js

markdown_extensions:
  - footnotes:
  - toc:
      permalink:

pages:
  - Home: index.md
  # - Legal-Ad-NorthShoreNow: publish.md
  # - Additional Lead Information: lead.md
